#!/bin/bash

# Get the process ID (PID) of AudioAlchemy.py
PID=$(pgrep -f './AudioAlchemy.py')

if [ -z "$PID" ]; then
    echo "The application audioalchemy is not running."
    exit 1
fi

# Kill the process with the extracted PID
sudo kill -9 $PID

# Verify if the process was successfully killed
if [ $? -eq 0 ]; then
    echo "Successfully killed the audioalchemy process with PID: $PID."
else
    echo "Failed to kill the audioalchemy process with PID: $PID."
fi
